name: Docker Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: warp-ubuntu-latest-x64-2x
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: false
          load: true
          tags: user/petclinic:${{ github.sha }}

      - name: Download and Setup facetsctl
        run: |
          wget https://facets-cf-templates.s3.amazonaws.com/oclif-tarballs/production/versions/1.0.8-5508370538/30c7d95/facetsctl-v1.0.8-5508370538-30c7d95-linux-x64.tar.gz
          tar -xzvf facetsctl-v1.0.8-5508370538-30c7d95-linux-x64.tar.gz

      - name: Login to facetsctl
        run: ./facetsctl/bin/facetsctl login -u ${{ secrets.FACETS_USERNAME }} -t ${{ secrets.FACETS_TOKEN }} -c https://pwc.console.facets.cloud

      - name: Push Image using facetsctl
        run: ./facetsctl/bin/facetsctl push -i user/petclinic:${{ github.sha }} -a petclinic -e ${{ github.sha }} --registration-type=RELEASE_STREAM --registration-value=DEV
